### PR TITLE
Fix stray pixels on focused inputs such as checkboxes and radios

### LINKED ISSUE #39: Radios has stray pixels in Firefox
image
Stray pixels appear when Radio cursor is blinking.

Does not appear in Google Chrome, the pixels appear in Firefox 63.0.3, even with different zoom levels.
Might just be a Firefox bug.

### PR DESCRIPTION
**Pull request by alexgleason**
Closes #39 

screenshot from 2018-11-30 11 59 00

You can see there are stray pixels between "Yes" and "No".

This also happens for the checkbox:

screenshot from 2018-11-30 12 02 28

This PR fixes the issue by setting `outline: 0` on all inputs. By default, most browsers will add an outline to `input:focused` elements. By setting `outline: 0`, we are overriding that behavior to remove the outline.

External links:
* [CSS `outline` on MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/outline).

### CODE REVIEW

**Comment by BcRikko** [comment]
Thanks 🙇 

`outline` is used in input fields. so I don't want to change `input { outline: 0 }` 😢 
outline

Are you pointing out that the color of `.radio` and `.checkbox` are gray color? 🤔 
If so, It's intentionally changing. ↓
https://github.com/BcRikko/NES.css/blob/master/scss/elements/checkboxes.scss#L3-L47
https://github.com/BcRikko/NES.css/blob/master/scss/elements/radios.scss#L3-L21

**Comment by trezy** [comment]
Hey @alexgleason, make sure to merge the latest version of the `develop` branch so that our CI will run the required checks for this PR. 😉

**Comment by evexoio** [comment]
I can't reproduce the stray pixels

radiofirefox

**Comment by BcRikko** [comment]
This change is not good 🙈 
because when focusing on input field, the outline disappears. 😢 

|this PR|expect|
|----|----|
|pr|expect|

**Comment by evexoio** [comment]
@BcRikko I'll push a PR to limit the `outline: 0` to radios and checkboxes only 🙌

**Pull request merged**
