### PR TITLE
feat: add favicon.ico

### PR DESCRIPTION
**Pull request by guastallaigor**
Not sure but what do you guys think about adding a `favicon.ico`?
I made it using the `snes-jp-logo`.

### CODE REVIEW

**Comment by BcRikko** [comment]
Good 👍 

`favicon.ico` is already in `./favicon.ico` 📁 
but it is a provisional icon.

so I'd like to change favicon to `snes-jp-logo` 👍 
Could you change the size of favicon to a square, and make the white part transparent?🤔

**Comment by guastallaigor** [comment]
Oh I didn't see that, because I think `index.html` was not pointing to that file.
I will need to work on this from home, so will take a while.
If anyone wants to address this sooner that's no problem :+1:

**Comment by guastallaigor** [comment]
This is what it looks like right now, is this ok?

image

image

**Pull request merged**
