### PR TITLE
add medium icon set

### PR DESCRIPTION
**Pull request by KeevanDance**
Added Medium (https://medium.com/) icon set found here: [Medium Branding](https://medium.design/logos-and-brand-guidelines-f1a01a733592)

If it needs more work, please give me what I can improve, and I will work more on it!

image

### CODE REVIEW

**Comment by BcRikko** [comment]
I was just about to point to same thing. 🔍 

well...

1. `npm install`
2. Cancel changes in `package-lock.json` before commit  👈 
3. address this PR.
4. `git add` and `git commit`
5. `git push`

Could you cancel `package-lock.json` changes before `git add`? 🤔

**Comment by KeevanDance** [comment]
hmm so strange

image


this seemed to fix it, but prevents Husky from doing precheck...?

**Comment by BcRikko** [comment]
Ok 👍 

`husky` will check coding style before committing. so you need `devDependencies` package.  📦 
could you remove `--production` flag, and execute `npm install --no-save`. 🙇

**Comment by KeevanDance** [comment]
@BcRikko Alright, it is fixed! Running `npm install --save-dev` instead of `npm i` fixed the issues... Not sure why? 🤔

**Comment by BcRikko** [comment]
Great 👍 

`i` of `npm i` is an alias for `install`. so `npm i --no-save` equals `npm install --no-save` 😄 

So if you execute `npm i --no-save`, you get the same result 🎉

**Comment by trezy** [comment]
Hey @KeevanDance, make sure to merge the latest version of the `develop` branch so that our CI will run the required checks for this PR. 😉

**Pull request merged**
