### PR TITLE
Change SNES controller to NES

### PR DESCRIPTION
**Pull request by SirDaev**
NES better represents 8-bit, and after all it is not called SNES.css

### CODE REVIEW

**Comment by BcRikko** [comment]
ref #5 

You're right 🙆
but, This is a joke framework.

I love SNES(SUPER Famicom) Controller, because I'm a SUPER Famicon Generation 😍
I would like to leave it unchanged.

What do you think? 🤔

**Comment by IngwiePhoenix** [comment]
Well I can totally understand you (I prefer NES, but I love a lot of SNES games). And, it really is your decision as an icon is what gives a project it’s identity.

Now, this is called NES.css and not SNES.css - that was already pointed out. So if the logo was to represent the name, it would have to be a NES controller. However, since you said that it’s just a fun project - or in your, translated, wording: a joke framework - I can also see a SNES controller as the logo, since it’s all about 8bit!

So in the end… this may turn out to be a very opinion-based discussion. You own this project, so you get to decide in the end :)

**Comment by SirDaev** [comment]
I guess the two points I wanted to make were 1) using the NES controller vs SNES, and 2) SNES is actually 16-bit. The SNES controller seems more of a ubiquitous icon for retro gaming, though. It could go wither way. Cool project anyway!

**Comment by IngwiePhoenix** [comment]
I definitively agree. But at the same moment, I am also not entirely sure myself.

But, I agree - this is a really cool project. Gonna make me a little blog-thingy off it for my personal website, because I love 8bit with one hell of a passion! :) So this design would just fit perfectly.

**Comment by drzaiusx11** [comment]
I think an improved NES icon would be better (visually the SNES one just looks better, but thats subjective)

I can git a try at a new NES one using the NES color palette

**Comment by narciar-ski** [comment]
both look nice!

**Comment by trezy** [comment]
Hey @SirDaev, make sure to merge the latest version of the `develop` branch so that our CI will run the required checks for this PR. 😉

**Comment by SirDaev** [comment]
@evexoio Thanks for merging that in 😃

**Comment by BcRikko** [comment]
I prefer `snes-jp-logo` 😍 
because I'm Japanese, I'm not familiar with NES controller.

Someone may say that the framework name is wrong... 😭 
but this is a fun project. so I'm not asking for accuracy 🙇

Is it no good? 😢

**Comment by evexoio** [comment]
@BcRikko its not a big issue really, lets keep it as is ❤️

@SirDaev We're keeping the logo as is for the love of the maker of this repo <3, thanks for contributing.

**Comment by drzaiusx11** [comment]
As you said you're not as familiar with the NES (and presumably its version of the controller), thats why I made an attempt at a more NES-like controller icon. 

But at the end of the day its your project and I respect your decision to keep it as-is. This is a very fun project, keep up the fantastic work! ❤️

**Comment by BcRikko** [comment]
Thank you for going along with what I wanted to do.  🙇 

Here's the story:

* I created a [8bit.css](https://bcrikko.github.io/css-collection/tool/8bit/index.html) 3 months ago (It's a draft version of NES.css) 🛠 
* `8bit` has the same recognition as `retro` among me, but it was too rich for `8bit`
* I renamed `8bit.css` to `NES.css` 📺 
* `NES` is affected by MOTHER2 👦 
* so `NES` of NES.css isn't exactly Nintendo Entertainment System 🎮 
*  MOTHER2 publlished for the SNES(SUPER Famicom)

This is the reason why I stick to SNES Controller. 🙏

**Pull request closed without merging**
