### PR TITLE
Add now.json to deploy PRs

### PR DESCRIPTION
**Pull request by styfle**
**Description**
Add a `now.json` config file so that PRs are deployed to ZEIT Now hosting.

This will require creating an account and adding the integration here: https://zeit.co/github

You can see how it looks by viewing existing PRs here: https://github.com/markedjs/marked

**Compatibility**
None. However you can get a nicer domain name for free such as nes.now.sh if you like.

**Caveats**
Takes a minute to setup but then there is no need to touch it after that.

### CODE REVIEW

**Comment by styfle** [comment]
I fixed the commit lint CI, thanks!

**Comment by BcRikko** [comment]
Thanks 😆 
I learned ZEIT for the first time. 👍 

But I don't want to change the URL of the demo page.
Because the current URL(https://nostalgic-css.github.io/NES.css/) is shared by many people.

Can I use ZEIT without changing the URL? 🤔

**Comment by styfle** [comment]
Yes, you can setup a redirect from GH Pages to a custom domain or a now.sh domain 

Something like the following should work on a gh-pages branch:

```
<!DOCTYPE html>
<meta charset="utf-8">
<title>Redirecting to https://example.com/</title>
<meta http-equiv="refresh" content="0; URL=https://example.com/">
<link rel="canonical" href="https://example.com/">
```

**Comment by BcRikko** [comment]
Thanks for your comment. 🙇 

Our gh-pages is  very small. There's no Slack integration. 📦 
So I couldn't find a clear reason to move to "ZEIT Now". 🤔 

Sorry... 😭

**Pull request closed without merging**
