### PR TITLE
Add icons linkedin and gmail

### PR DESCRIPTION
**Pull request by guastallaigor**
This address #175 .

image

Also added to storybook.

### CODE REVIEW

**Comment by BcRikko** [comment]
Do you think it would be better to round the four corners of the Gmail logo? 🤔 
https://github.com/nostalgic-css/NES.css/issues/65#issuecomment-444165422

**Comment by guastallaigor** [comment]
@BcRikko I think so, I will make it rounded, forgot about that.

**Comment by guastallaigor** [comment]
Removed the corners:

image

**Comment by BcRikko** [comment]
Great 🎉 

`package-lock.json` has been changed
Could you return `package-lock.json` to its original state? 🤔

**Pull request merged**
