### PR TITLE
Issue and Pull Request templates

### PR DESCRIPTION
**Pull request by IngwiePhoenix**
# Description
This pull request introduces template files which can be used to template future issues and PRs. They may allow a user to structure their post and allows for issues and PRs to be more streamline, especially useful during a mass-processing of many of such tickets!

# Compatibility
This does not break anything and does not affect the CSS in any way. However, it improves issues and PRs.

# Caveats
This post already uses the new template! :)

### CODE REVIEW

**Comment by BcRikko** [comment]
thanks 🙇 
I think it would comment out `<` and `>` better.
like below.
```md
<!-- Please fill your information below the lines starting with `#`. -->
<!-- You can delete these lines enclosed by `<` and `>` before posting, too. -->

# Description of the issue
<!-- What is the issue/problem you are facing? -->

# What was expected to be seen
<!-- What were you expecting to see? -->

# What actually was seen instead
<!-- What did you actually see? Try to be precise as possible! -->

# Environment
Browser: <!-- Version of your browser. -->
Build environment (i.e. NodeJS): <!-- If you have issues building the SCSS into CSS, add your information here. Delete this otherwise. -->

# Suggestion(s) for fixing this issue
<!-- What are your thoughts? How could this possibly be resolved? -->
```

|before|after|
|----|----|
|before|after|


and about `Description of the issue`
I want to select `issue type` from list. 🔍 

* bug
* feature request
* other

like issue of vuejs project. ✌️ -> https://new-issue.vuejs.org/?repo=vuejs/vue

what do you think? 🤔

**Comment by IngwiePhoenix** [comment]
Oi, I actually did not know that! Arigatō :) (Yeah, I only know two things in japanese, saying hellow and thank you.)

I will fix this ASAP. I wasn't aware that HTML comments actually worked in Github flavored Markdown!

**Comment by IngwiePhoenix** [comment]
For some reason, i needed to merge an updated "circleci.yml"... I have no idea where that came from, but it did. Any idea here @trezy ?

Anyway, updated the comments.

**Comment by IngwiePhoenix** [comment]
Also I unfortunately have no idea how the multiple issue-types work... I never used Github to tht extend that I sat this up for any of my projects - ever.

**Comment by trezy** [comment]
Hey @IngwiePhoenix , make sure to merge the latest version of the `develop` branch so that our CI will run the required checks for this PR. 😉

**Comment by IngwiePhoenix** [comment]
I did. Look, there is a merge commit. :) But just to be sure I'll pull and push again.

**Comment by trezy** [comment]
Sorry, @IngwiePhoenix, we had CI turned off for forked PRs. I've fixed this and updated the branch, so CI is running now. 😁

**Comment by IngwiePhoenix** [comment]
Alright. :)

**Comment by trezy** [comment]
I think this PR is good as is. I also love the idea of the issue helper, but I don’t think it should hold up this PR. @BcRikko, would you mind creating an issue for it since you started on a demo for it and should have a good idea of what you want to see? 😁

**Pull request merged**
