### PR TITLE
add .is-rounded class

### PR DESCRIPTION
**Pull request by loo41**

### CODE REVIEW

**Comment by evexoio** [comment]
safari

This doesn't look right on safari.

**Comment by evexoio** [comment]
chrome

What's this border inside the button?

**Comment by BcRikko** [comment]
It's the work of **user agent stylesheet** of Safari 👿 
I solve it with `border: none;`, but I'm not sure the side effects.

Please give me time to investigate. 🙏

**Comment by jjspace** [comment]
It's in the **user agent stylesheet** of Chrome as well. I dont think there should be a problem with removing the border from buttons. That's a pretty standard first step to restyling them.

**Comment by loo41** [comment]
It's border: none. Last time PR was there, border: none was written under. bnt and fixed a little bit of the white edge problem.     .v__v

**Comment by BcRikko** [comment]
I answered -> https://github.com/nostalgic-css/NES.css/issues/86#issuecomment-445501451

@jjspace Thanks, You are right 👍

**Pull request merged**
