### PR TITLE
fix(containers.scss): fix alignment of title

### PR DESCRIPTION
**Pull request by BcRikko**
Many changes have been detected, but I just fixed margin of `is-center > .title` and properties order. 🛠 

|before|after|
|----|----|
|container|after|

### CODE REVIEW

**Comment by jjspace** [comment]
LGTM but I can't officially add my review without being in the org

**Comment by evexoio** [comment]
### With title: looks good 👍
with-title

### With title, is rounded: is this intended behavior?
is-rounded-with-title

**Comment by BcRikko** [comment]
umm……
After pulling `fix-alignment-of-title` and rebuilding it,
then it looks like the image below in my environment. 🤔 
alignment

**Comment by BcRikko** [comment]
I fixed it 🛠

**Pull request merged**
