### PR TITLE
Release v2.x 🚀

### PR DESCRIPTION
**Pull request by BcRikko**
Minor update(bug fix) & Security update📦 🚀 

* [x] #344

### CODE REVIEW

**Comment by trezy** [comment]
I'd like to request that we hold off on the 2.0 release until we've updated the library to remove the current icons and replaced them with NES.icons. This is because the NES.icons library has some collision issues with NES.css due to icon class names being the same. I'm hoping to have the NES.icons site done and up sometime this week. After that, I'll work on getting a PR in to NES.css to update the icons. 😁

**Comment by BcRikko** [comment]
This PR is a minor update that includes security updates and bug fixes. 👮 
And v2.x has been released. so the current version of NES.css is v2.1.1.

Removing icons from NES.css has a big impact, so I'd like to work on it in [the Next version](https://github.com/nostalgic-css/NES.css/issues/331) 🚀 
Until then, it's better to load `nes-core.css` and use it.

```html
<link href="https://unpkg.com/nes.css@latest/css/nes-core.min.css" rel="stylesheet" />
<link href="https://unpkg.com/nes.icons@latest/css/nes.min.css" rel="stylesheet" />
```

What do you think? 🤔

**Comment by guastallaigor** [comment]
> @BcRikko Yup, that makes sense. I was under the impression that we were still on v1.x.

We also thought that when we made the last release :smile:, but I think `semantic-release` put the version in 2.x because of some breaking changes.

**Pull request merged**
