### PR TITLE
feat(icon): add discord icon 16x16

### PR DESCRIPTION
**Pull request by omurilo**
**Description**

This PR add a discord icon on SES.css asked in #412, I met this project today and decided to contribute. 

Discord Icon 16x16

**Compatibility**

No breaking changes. Just an Icon added to develop branch.

### CODE REVIEW

**Review by marcobrunodev — COMMENTED** [review]
Nice. I want! :+1:

**Comment by guastallaigor** [comment]
As much as I would like this icon, I don't have authorization to merge any new icons.
References: 
- https://github.com/nostalgic-css/NES.css/pull/410#issuecomment-601461677
- https://github.com/nostalgic-css/NES.css/issues/310#issuecomment-469073437

So we will need to wait for the creator in this one.
I will make a new PR to all README.md regarding this.
I do apologize for the delay.

**Comment by stanleynguyen** [comment]
Any updates on this?

**Comment by devanoneth** [comment]
In case anyone wants, I cloned the forked branch and built the SCSS. If you add the below code into your own CSS you can use it:

```
.nes-icon.discord::before {
  width: 1px;
  height: 1px;
  color: #7298da;
  box-shadow: 2px 1px,3px 1px,4px 1px,5px 1px,6px 1px,7px 1px,8px 1px,9px 1px,10px 1px,11px 1px,12px 1px,13px 1px,14px 1px,15px 1px,1px 2px,2px 2px,3px 2px,4px 2px,5px 2px,6px 2px,7px 2px,8px 2px,9px 2px,10px 2px,11px 2px,12px 2px,13px 2px,14px 2px,15px 2px,16px 2px,1px 3px,2px 3px,3px 3px,4px 3px,5px 3px #fff,6px 3px #fff,7px 3px #fff,8px 3px,9px 3px,10px 3px #fff,11px 3px #fff,12px 3px #fff,13px 3px,14px 3px,15px 3px,16px 3px,1px 4px,2px 4px,3px 4px,4px 4px #fff,5px 4px #fff,6px 4px,7px 4px,8px 4px,9px 4px,10px 4px,11px 4px,12px 4px #fff,13px 4px #fff,14px 4px,15px 4px,16px 4px,1px 5px,2px 5px,3px 5px #fff,4px 5px #fff,5px 5px,6px 5px #fff,7px 5px #fff,8px 5px #fff,9px 5px #fff,10px 5px #fff,11px 5px #fff,12px 5px,13px 5px #fff,14px 5px #fff,15px 5px,16px 5px,1px 6px,2px 6px,3px 6px #fff,4px 6px #fff,5px 6px #fff,6px 6px #fff,7px 6px #fff,8px 6px #fff,9px 6px #fff,10px 6px #fff,11px 6px #fff,12px 6px #fff,13px 6px #fff,14px 6px #fff,15px 6px,16px 6px,1px 7px,2px 7px #fff,3px 7px #fff,4px 7px #fff,5px 7px,6px 7px,7px 7px #fff,8px 7px #fff,9px 7px #fff,10px 7px #fff,11px 7px,12px 7px,13px 7px #fff,14px 7px #fff,15px 7px #fff,16px 7px,1px 8px,2px 8px #fff,3px 8px #fff,4px 8px,5px 8px,6px 8px,7px 8px,8px 8px #fff,9px 8px #fff,10px 8px,11px 8px,12px 8px,13px 8px,14px 8px #fff,15px 8px #fff,16px 8px,1px 9px,2px 9px #fff,3px 9px #fff,4px 9px,5px 9px,6px 9px,7px 9px,8px 9px #fff,9px 9px #fff,10px 9px,11px 9px,12px 9px,13px 9px,14px 9px #fff,15px 9px #fff,16px 9px,1px 10px,2px 10px #fff,3px 10px #fff,4px 10px #fff,5px 10px,6px 10px,7px 10px #fff,8px 10px #fff,9px 10px #fff,10px 10px #fff,11px 10px,12px 10px,13px 10px #fff,14px 10px #fff,15px 10px #fff,16px 10px,1px 11px,2px 11px #fff,3px 11px #fff,4px 11px #fff,5px 11px #fff,6px 11px #fff,7px 11px #fff,8px 11px #fff,9px 11px #fff,10px 11px #fff,11px 11px #fff,12px 11px #fff,13px 11px #fff,14px 11px #fff,15px 11px #fff,16px 11px,1px 12px,2px 12px #fff,3px 12px #fff,4px 12px #fff,5px 12px #fff,6px 12px,7px 12px #fff,8px 12px #fff,9px 12px #fff,10px 12px #fff,11px 12px,12px 12px #fff,13px 12px #fff,14px 12px #fff,15px 12px #fff,16px 12px,1px 13px,2px 13px,3px 13px #fff,4px 13px #fff,5px 13px #fff,6px 13px #fff,7px 13px,8px 13px,9px 13px,10px 13px,11px 13px #fff,12px 13px #fff,13px 13px #fff,14px 13px #fff,15px 13px,16px 13px,1px 14px,2px 14px,3px 14px,4px 14px #fff,5px 14px #fff,6px 14px,7px 14px,8px 14px,9px 14px,10px 14px,11px 14px,12px 14px #fff,13px 14px #fff,14px 14px,15px 14px,16px 14px,1px 15px,2px 15px,3px 15px,4px 15px,5px 15px,6px 15px,7px 15px,8px 15px,9px 15px,10px 15px,11px 15px,12px 15px,13px 15px,14px 15px,15px 15px,16px 15px,2px 16px,3px 16px,4px 16px,5px 16px,6px 16px,7px 16px,8px 16px,9px 16px,10px 16px,11px 16px,12px 16px,13px 16px,14px 16px,15px 16px;
}

@supports (-moz-appearance: meterbar) {
  .nes-icon.discord::before {
    box-shadow: 2px 1px 0 0.020em,3px 1px 0 0.020em,4px 1px 0 0.020em,5px 1px 0 0.020em,6px 1px 0 0.020em,7px 1px 0 0.020em,8px 1px 0 0.020em,9px 1px 0 0.020em,10px 1px 0 0.020em,11px 1px 0 0.020em,12px 1px 0 0.020em,13px 1px 0 0.020em,14px 1px 0 0.020em,15px 1px 0 0.020em,1px 2px 0 0.020em,2px 2px 0 0.020em,3px 2px 0 0.020em,4px 2px 0 0.020em,5px 2px 0 0.020em,6px 2px 0 0.020em,7px 2px 0 0.020em,8px 2px 0 0.020em,9px 2px 0 0.020em,10px 2px 0 0.020em,11px 2px 0 0.020em,12px 2px 0 0.020em,13px 2px 0 0.020em,14px 2px 0 0.020em,15px 2px 0 0.020em,16px 2px 0 0.020em,1px 3px 0 0.020em,2px 3px 0 0.020em,3px 3px 0 0.020em,4px 3px 0 0.020em,5px 3px 0 0.020em #fff,6px 3px 0 0.020em #fff,7px 3px 0 0.020em #fff,8px 3px 0 0.020em,9px 3px 0 0.020em,10px 3px 0 0.020em #fff,11px 3px 0 0.020em #fff,12px 3px 0 0.020em #fff,13px 3px 0 0.020em,14px 3px 0 0.020em,15px 3px 0 0.020em,16px 3px 0 0.020em,1px 4px 0 0.020em,2px 4px 0 0.020em,3px 4px 0 0.020em,4px 4px 0 0.020em #fff,5px 4px 0 0.020em #fff,6px 4px 0 0.020em,7px 4px 0 0.020em,8px 4px 0 0.020em,9px 4px 0 0.020em,10px 4px 0 0.020em,11px 4px 0 0.020em,12px 4px 0 0.020em #fff,13px 4px 0 0.020em #fff,14px 4px 0 0.020em,15px 4px 0 0.020em,16px 4px 0 0.020em,1px 5px 0 0.020em,2px 5px 0 0.020em,3px 5px 0 0.020em #fff,4px 5px 0 0.020em #fff,5px 5px 0 0.020em,6px 5px 0 0.020em #fff,7px 5px 0 0.020em #fff,8px 5px 0 0.020em #fff,9px 5px 0 0.020em #fff,10px 5px 0 0.020em #fff,11px 5px 0 0.020em #fff,12px 5px 0 0.020em,13px 5px 0 0.020em #fff,14px 5px 0 0.020em #fff,15px 5px 0 0.020em,16px 5px 0 0.020em,1px 6px 0 0.020em,2px 6px 0 0.020em,3px 6px 0 0.020em #fff,4px 6px 0 0.020em #fff,5px 6px 0 0.020em #fff,6px 6px 0 0.020em #fff,7px 6px 0 0.020em #fff,8px 6px 0 0.020em #fff,9px 6px 0 0.020em #fff,10px 6px 0 0.020em #fff,11px 6px 0 0.020em #fff,12px 6px 0 0.020em #fff,13px 6px 0 0.020em #fff,14px 6px 0 0.020em #fff,15px 6px 0 0.020em,16px 6px 0 0.020em,1px 7px 0 0.020em,2px 7px 0 0.020em #fff,3px 7px 0 0.020em #fff,4px 7px 0 0.020em #fff,5px 7px 0 0.020em,6px 7px 0 0.020em,7px 7px 0 0.020em #fff,8px 7px 0 0.020em #fff,9px 7px 0 0.020em #fff,10px 7px 0 0.020em #fff,11px 7px 0 0.020em,12px 7px 0 0.020em,13px 7px 0 0.020em #fff,14px 7px 0 0.020em #fff,15px 7px 0 0.020em #fff,16px 7px 0 0.020em,1px 8px 0 0.020em,2px 8px 0 0.020em #fff,3px 8px 0 0.020em #fff,4px 8px 0 0.020em,5px 8px 0 0.020em,6px 8px 0 0.020em,7px 8px 0 0.020em,8px 8px 0 0.020em #fff,9px 8px 0 0.020em #fff,10px 8px 0 0.020em,11px 8px 0 0.020em,12px 8px 0 0.020em,13px 8px 0 0.020em,14px 8px 0 0.020em #fff,15px 8px 0 0.020em #fff,16px 8px 0 0.020em,1px 9px 0 0.020em,2px 9px 0 0.020em #fff,3px 9px 0 0.020em #fff,4px 9px 0 0.020em,5px 9px 0 0.020em,6px 9px 0 0.020em,7px 9px 0 0.020em,8px 9px 0 0.020em #fff,9px 9px 0 0.020em #fff,10px 9px 0 0.020em,11px 9px 0 0.020em,12px 9px 0 0.020em,13px 9px 0 0.020em,14px 9px 0 0.020em #fff,15px 9px 0 0.020em #fff,16px 9px 0 0.020em,1px 10px 0 0.020em,2px 10px 0 0.020em #fff,3px 10px 0 0.020em #fff,4px 10px 0 0.020em #fff,5px 10px 0 0.020em,6px 10px 0 0.020em,7px 10px 0 0.020em #fff,8px 10px 0 0.020em #fff,9px 10px 0 0.020em #fff,10px 10px 0 0.020em #fff,11px 10px 0 0.020em,12px 10px 0 0.020em,13px 10px 0 0.020em #fff,14px 10px 0 0.020em #fff,15px 10px 0 0.020em #fff,16px 10px 0 0.020em,1px 11px 0 0.020em,2px 11px 0 0.020em #fff,3px 11px 0 0.020em #fff,4px 11px 0 0.020em #fff,5px 11px 0 0.020em #fff,6px 11px 0 0.020em #fff,7px 11px 0 0.020em #fff,8px 11px 0 0.020em #fff,9px 11px 0 0.020em #fff,10px 11px 0 0.020em #fff,11px 11px 0 0.020em #fff,12px 11px 0 0.020em #fff,13px 11px 0 0.020em #fff,14px 11px 0 0.020em #fff,15px 11px 0 0.020em #fff,16px 11px 0 0.020em,1px 12px 0 0.020em,2px 12px 0 0.020em #fff,3px 12px 0 0.020em #fff,4px 12px 0 0.020em #fff,5px 12px 0 0.020em #fff,6px 12px 0 0.020em,7px 12px 0 0.020em #fff,8px 12px 0 0.020em #fff,9px 12px 0 0.020em #fff,10px 12px 0 0.020em #fff,11px 12px 0 0.020em,12px 12px 0 0.020em #fff,13px 12px 0 0.020em #fff,14px 12px 0 0.020em #fff,15px 12px 0 0.020em #fff,16px 12px 0 0.020em,1px 13px 0 0.020em,2px 13px 0 0.020em,3px 13px 0 0.020em #fff,4px 13px 0 0.020em #fff,5px 13px 0 0.020em #fff,6px 13px 0 0.020em #fff,7px 13px 0 0.020em,8px 13px 0 0.020em,9px 13px 0 0.020em,10px 13px 0 0.020em,11px 13px 0 0.020em #fff,12px 13px 0 0.020em #fff,13px 13px 0 0.020em #fff,14px 13px 0 0.020em #fff,15px 13px 0 0.020em,16px 13px 0 0.020em,1px 14px 0 0.020em,2px 14px 0 0.020em,3px 14px 0 0.020em,4px 14px 0 0.020em #fff,5px 14px 0 0.020em #fff,6px 14px 0 0.020em,7px 14px 0 0.020em,8px 14px 0 0.020em,9px 14px 0 0.020em,10px 14px 0 0.020em,11px 14px 0 0.020em,12px 14px 0 0.020em #fff,13px 14px 0 0.020em #fff,14px 14px 0 0.020em,15px 14px 0 0.020em,16px 14px 0 0.020em,1px 15px 0 0.020em,2px 15px 0 0.020em,3px 15px 0 0.020em,4px 15px 0 0.020em,5px 15px 0 0.020em,6px 15px 0 0.020em,7px 15px 0 0.020em,8px 15px 0 0.020em,9px 15px 0 0.020em,10px 15px 0 0.020em,11px 15px 0 0.020em,12px 15px 0 0.020em,13px 15px 0 0.020em,14px 15px 0 0.020em,15px 15px 0 0.020em,16px 15px 0 0.020em,2px 16px 0 0.020em,3px 16px 0 0.020em,4px 16px 0 0.020em,5px 16px 0 0.020em,6px 16px 0 0.020em,7px 16px 0 0.020em,8px 16px 0 0.020em,9px 16px 0 0.020em,10px 16px 0 0.020em,11px 16px 0 0.020em,12px 16px 0 0.020em,13px 16px 0 0.020em,14px 16px 0 0.020em,15px 16px 0 0.020em;
  }
}
```

**Review by abdallahalsamman — APPROVED** [review]
nice, looks good to me

**Comment by omurilo** [comment]
Hi, CircleCI failed tests failed with other issues that have no association with this PR, right? So PR can be to merge?

**Comment by omurilo** [comment]
Hello, I'll close this PR because I think that project is abandoned.

**Comment by BcRikko** [comment]
@omurilo Thanks comment.

To be honest, this project is stalled because I don't have the time or money to maintain OSS development. 😢 
Sorry...

ref https://x.com/IngwiePhoenix/status/1794496416158511504

**Pull request closed without merging**
