### PR TITLE
Grammar and misc fixes to README

### PR DESCRIPTION
**Pull request by ohlookitsderpy**
**Description**
Fixes some grammar issues related to the README file.

**Compatibility**
Shouldn't break anything!

**Caveats**
None that I know of.

### CODE REVIEW

**Comment by ohlookitsderpy** [comment]
Ran the commands, accidentally forgot to copy the ``e`` on the end of the first one. Is there any way I can fix this?

**Comment by BcRikko** [comment]
Umm...
It's troublesome, so it's ok as it is 👍 

----

If you do, it is the following command:
```bash
$ git rebase -i HEAD~4

# edit commit message

$ git commit --amend
$ git rebase --continue
```

**Comment by ohlookitsderpy** [comment]
no problem!

**Pull request merged**
