### PR TITLE
feat(icons): add phone and smartphone icons

### LINKED ISSUE #65: More icons
Is there any way we can get more social-media icons? Like Gmail, Youtube, and phone number? :heart: 
Or how can i make it?

- [X] Medium
- [X] Twitch
- [X] Google
- [X] Youtube
- [x] Phone

### PR DESCRIPTION
**Pull request by guastallaigor**
Please check if this icons is ok to close #65 :

image

### CODE REVIEW

**Comment by jjspace** [comment]
That looks much better, I like it. 
One other comment I thought of for the handheld is that many icon libraries will portray it diagonally like [fa](https://fontawesome.com/v4.7.0/icon/phone), [Noun project](https://thenounproject.com/search/?q=phone&i=2079209), and [flat-icon](https://www.flaticon.com/free-icon/phone-receiver_9243#term=phone&page=1&position=2). Might be worth looking into

**Comment by guastallaigor** [comment]
@jjspace Yeah I know, but that's a lot harder to make for me :laughing: . But I will give it a shot.

**Comment by jjspace** [comment]
Haha yea I know so don't worry about it too much, just a thought

**Comment by guastallaigor** [comment]
@jjspace But I got an idea, what if I just rotate it -45deg? What do you think of this?

image

**Comment by jjspace** [comment]
First off I think that handheld looks much better with the style we've been creating, nice job!

As for rotating I'm not sure how I feel about it, might need others opinions on it. My thoughts are that I'm hesitant to use the transform and would kinda rather let the consumer do that themselves if they want it. But in addition to that it doesn't exactly make sense from a pixel art perspective. You cant just reach into a screen and rotate how it draws pixels or the arrangement of leds in a screen so it doesn't exactly make sense to have diagonal lines like that.

**Pull request merged**
