### PR TITLE
add sites using NES.css to README.md

### PR DESCRIPTION
**Pull request by evexoio**
Implements #38 

[You can see this PR's version of README.md at my fork](https://github.com/evexoio/NES.css/tree/38-add-sites-using-nes.css)

### CODE REVIEW

**Comment by BcRikko** [comment]
I think that it's better to add `sites using NES.css` to another file or demo page or another repo than to add it to README.md. 🤔 
like this -> https://github.com/vuejs-jp/who-use-vuejs-in-japan

I want to keep `README.md` simple 👍

**Comment by zetaraku** [comment]
I think a demo page or even a screenshot is really helpful for  quickly previewing what it will look like. :wink:

**Comment by evexoio** [comment]
@BcRikko we still have only one website that is using NES.css, the others(trezy's pixel editor, is there any else?) are not in production yet.

I'll close this until there is at least 5 sites using NES.css so it improves credibility of NES.css instead of the other way around(not many sites using NES.css means NES.css is not worthy).

**Comment by BcRikko** [comment]
I see 👍

**Pull request closed without merging**
