### PR TITLE
Added Korean translation of CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by tank3a**
# 464 Issue

Added Korean translation of CONTRIBUTING.md and added `CONTRIBUTING-ko` link to other versions of CONTRIBUTING.

### CODE REVIEW

**Comment by tank3a** [comment]
What does it mean by
✖   subject may not be empty [subject-empty]
✖   type may not be empty [type-empty]
from failed details?

**Comment by guastallaigor** [comment]
Hey @tank3a 

Unfortunately commitlint has failed.

Could you change your commit message to something like `docs: add korean contributing translation file` 🙇

`````sh
# edit your commit message
$ git commit --amend -m "docs: add korean contributing translation file"

# force push branch
$ git push --force-with-lease origin update-docs

**Review by guastallaigor — APPROVED** [review]
LGTM 👍 
I can't really review the korean translations, but I will take your word for it 😄 
Just please fix the commit message to pass commitlint and I will merge it.

**Comment by tank3a** [comment]
I guess I changed.. or maybe messed up, but now the test is passed! Thank you!

**Pull request merged**
