### PR TITLE
Add google icon

### PR DESCRIPTION
**Pull request by guastallaigor**
If you think it's fine here it is. Otherwise I can make some changes.

image

One more for #65 .

### CODE REVIEW

**Comment by BcRikko** [comment]
Thanks 🙇 
LGTM 🎉

**Comment by BcRikko** [comment]
I counted the number of bytes in nes.min.css. 🔍
I was suprised that every time adding an icon, the file size of nes.min.css increases by about 33 KB. 

so please give me some time to merge your PR 🙇

**Comment by trezy** [comment]
Hey @guastallaigor, make sure to merge the latest version of the `develop` branch so that our CI will run the required checks for this PR. 😉

**Comment by guastallaigor** [comment]
I need some time to fix the commit history with this PR and resolve conflicts with develop. After work I will do it and get back to you. Thank you.

**Comment by guastallaigor** [comment]
I will close because I opened a new one (#96).

**Pull request closed without merging**
