### PR TITLE
Release v2.x

### PR DESCRIPTION
**Pull request by BcRikko**
Update 📦🚀

### CODE REVIEW

**Comment by BcRikko** [comment]
Thanks 🙇 

## 1. About #366, we should add an example inside the demo page (docs/index.html).

I'll add the component to the demo page before release. 👍 

## 2. If you know which version number is going to be, please update all the README unpkg link version.

To reduce future editing work. `@ latest` sounds like a good choice.
However, `@latest` will remain old for a few hours after release.

**Comment by HiKaylum** [comment]
Ill add it to the demo page tomorrow. I was waiting for the v2.0 release :)

**Comment by HiKaylum** [comment]
__REF__ #382

**Comment by BcRikko** [comment]
@HiKaylum Thanks for your contribute 😆 
That's very helpful. 👍

**Comment by HiKaylum** [comment]
> @HiKaylum Thanks for your contribute 😆
> That's very helpful. 👍

I have more stuff coming post this release 😝

**Comment by BcRikko** [comment]
Let's release 🚀 GO, GO 👍

**Pull request merged**
