### PR TITLE
feat(icons): add whatsapp icon

### PR DESCRIPTION
**Pull request by guastallaigor**
image

### CODE REVIEW

**Comment by evexoio** [comment]
@guastallaigor This is too pixelated. can we do better? It doesn't feel right 🙏

**Comment by guastallaigor** [comment]
@evexoio Not sure what to do.. I grab the idea from [here](http://pixelartmaker.com/art/a1b6b09a5379357). But I will think of something or do some research on it.

**Comment by jjspace** [comment]
@guastallaigor I think that one you linked works a little better because the phone handle is thicker and the circle seems more smoothed out, specifically the top right corner. Any reason we can't just use that design?

**Comment by guastallaigor** [comment]
> @guastallaigor I think that one you linked works a little better because the phone handle is thicker and the circle seems more smoothed out, specifically the top right corner. Any reason we can't just use that design?

None, I just didn't want to make a copy :smile: but that's fine I will do it.

**Comment by guastallaigor** [comment]
Now I think it looks like the image I provided:

image

**Pull request merged**
