### PR TITLE
Add Chinese simplified translation for README.

### PR DESCRIPTION
**Pull request by kenshinji**
I created Chinese translation for README. :)

### CODE REVIEW

**Comment by trezy** [comment]
Hey @kenshinji, thanks so much for the translation! However, we just updated all of our docs and made sure we had several translations for them. 😬 

Would you mind pulling down the `update-docs` branch and working off of that? We need an updated `README-zh-CN.md`, `CONTRIBUTING-zh-CN.md`, and `CODE_OF_CONDUCT-zh-CN.md`. If you could also add links all of the other docs, that would be amazing. ❤️

**Comment by kenshinji** [comment]
Ok, will do that later ;)

**Comment by trezy** [comment]
Just a heads up, @kenshinji, we’ve just merged the new versions of all of our documents. Make sure to pull down the `develop` branch and work off of that. 😉

**Comment by trezy** [comment]
Hey @kenshinji, were you able to update the translated docs?

**Comment by kenshinji** [comment]
@trezy yeah, sure, crazy busy these days, I'll update it before the end of this week, good?

**Comment by kenshinji** [comment]
@trezy I created a new PR here https://github.com/nostalgic-css/NES.css/pull/225, pls help me to review and merge, thanks.

**Pull request closed without merging**
