### PR TITLE
Add empty trophy icon and is-small modifier

### PR DESCRIPTION
**Pull request by Kartones**
- Adds a `is-small` css modifier (like `is-medium` or `is-large`) that renders at half the resolution (16x16 instead of 32x32). I plan to use it for certain places like icons at the footer or at container titles if those are small.
- Adds empty version of the trophy icon

Screenshot with the `is-small` version before the standard one:
image

### CODE REVIEW

**Comment by guastallaigor** [comment]
@Kartones Hello, I think you will need to change the base-branch to `develop`, and make sure it is up to date, so that our CI will run the required checks for this PR.

**Comment by Kartones** [comment]
:+1: no problem, will do!

**Comment by evexoio** [comment]
@Kartones Thanks for the PR! I've set the base branch to `develop`(@guastallaigor thanks).

can you please merge `develop` to your branch?

**Comment by Kartones** [comment]
Properly done at https://github.com/nostalgic-css/NES.css/pull/126

**Pull request closed without merging**
