### PR TITLE
feat(tables): it replicates the responsive tables from bootstrap

### PR DESCRIPTION
**Pull request by 4k1k0**
I use a `overflow-x: scroll` in the `<div>` that contains the `table`. This way the table doesn't break its container when you see it on mobile.

captura de pantalla_2018-12-10_23-39-30

### CODE REVIEW

**Comment by BcRikko** [comment]
Thanks 🙇 

sorry, NES.css only provides components. 
I don't want to provide a `xxx-container` style. 😢 

Because providing a layout style makes the framework big and complicated.

but your idea is great 👍 
Could you add the style below? 😆 
```css
@media screen and (max-width: 768px) {
    ...
    div.tables {
        overflow-x: auto;
    }
    ...
}
```
https://github.com/nostalgic-css/NES.css/blob/8acab18bfdf5fd5119a883e6e17e2bad8131b59f/style.css#L90-L105

**Comment by trezy** [comment]
@BcRikko I'd say this is a good addition to the framework. It's an opt-in style, so it's not going to affect all tables. Also, it only adds 3 lines to the framework.

**Comment by BcRikko** [comment]
OK, I see 👍 

Could you fix the following points 🙏 

* remove the media query
* use `auto` instead of `scroll`
   ```scss
   // tables.scss
   .nes-table-responsive {
     max-width: 100%;
     overflow-x: auto;
     overflow-y: hidden;
   }
   ```
* modify `Thou hast had a good afternoon` according to others and like `Thou hast had a good evening`, `Thou hast had a good night`
* review the `div.tables` style of `style.css`
  https://github.com/nostalgic-css/NES.css/blob/8acab18bfdf5fd5119a883e6e17e2bad8131b59f/style.css#L19-L30
  https://github.com/nostalgic-css/NES.css/blob/8acab18bfdf5fd5119a883e6e17e2bad8131b59f/style.css#L95-L98

**Comment by BcRikko** [comment]
@4k1k0 If you remove this part, I can merge. 😆 
Could you remove it? 🙏 
https://github.com/nostalgic-css/NES.css/blob/8acab18bfdf5fd5119a883e6e17e2bad8131b59f/style.css#L19-L30
https://github.com/nostalgic-css/NES.css/blob/8acab18bfdf5fd5119a883e6e17e2bad8131b59f/style.css#L95-L98

**Pull request merged**
