### PR TITLE
(breaking changes)Add prefix to class name

### LINKED ISSUE #6: Add prefix to class name
## ⚠️Breaking changes⚠️ 

Since NES.css doesn't provide layout. It maybe conflict when NES.css using the common class name.
Maybe add a prefix like ns- or nes- to solve this.

レイアウト関連のスタイルは提供していないためユーザ任せになる。そのときにNES.cssで汎用的なクラス名を使っているとコンフリクトする可能性がある。

`ns-`、`nes-`みたいなprefixをつけてコンフリクトを解消したい 🤔 

```html
<!-- ユーザ定義（.container） -->
<section class="container">
    <!-- NES.css (.ns-container.with-title) -->
    <section class="ns-container with-title">
    </section>
</section>
```

### PR DESCRIPTION
**Pull request by BcRikko**
## ⚠️ Breaking changes ⚠️ 

close #6 

* [x] add "nes-"
  * [x] 追加分の対応
* [x] fix demo page
* [x] fix storybook
* [x] #133 
* [x] #142

## 🙏 Please marge #133 first. next, I'll fix this PR(`style.css`). 🙏

### CODE REVIEW

**Comment by trezy** [comment]
@BcRikko The other 2 PRs you requested to have finished before this one are now taken care of. 😉

**Comment by evexoio** [comment]
@trezy thanks.

@BcRikko can you fix the conflicts please?

**Comment by BcRikko** [comment]
Tasks still remains. I'll do it today 👍 
please wait a moment 🙇

**Comment by tlynetteb** [comment]
hello

**Comment by tlynetteb** [comment]
https://github.com/tlynetteb/super-happiness.git

**Comment by BcRikko** [comment]
I did it 🛠

**Comment by BcRikko** [comment]
@tlynetteb hello 👋 

by the way, what is the URL of repository you commented? 🤔

**Pull request merged**
