### PR TITLE
add reddit icon

### PR DESCRIPTION
**Pull request by KeevanDance**
Reddit icon! Let me know if there is anything to change. I know you are planning on making a separate repository for icons, so I am just trying to create the most common ones I can think of.

image

### CODE REVIEW

**Comment by KeevanDance** [comment]
No Problem! 😄

**Comment by trezy** [comment]
Hey @KeevanDance, make sure to merge the latest version of the `develop` branch so that our CI will run the required checks for this PR. 😉

**Comment by KeevanDance** [comment]
@trezy I will try and get around to it this weekend! Also, would you prefer I submit the code to the other repository? or?

**Comment by evexoio** [comment]
@keevanDance you dont have to anymore, I merged develop to your PR’s branch 🙌🏼

**Comment by KeevanDance** [comment]
@evexoio TYSM <3

**Pull request merged**
