### PR TITLE
remove and untrack css

### LINKED ISSUE #97: Remove and ignore css
According to this comment https://github.com/nostalgic-css/NES.css/issues/13#issuecomment-443428179

We should remove and untrack css files.

### PR DESCRIPTION
**Pull request by evexoio**
closes #97 

No more css conflicts everybodyyy 🎉 🎉

### CODE REVIEW

**Comment by evexoio** [comment]
@trezy the goal of this PR was to get rid of conflicts caused by the css build, adding `css` to `.npmignore` is not going to solve that.

Does this go inline with what you were saying? or have I misunderstood you at some point?

**Comment by trezy** [comment]
@evexoio Yeah, I think you misunderstood. Here are what the two files should look like when you're done:

**.gitignore**
```
node_modules
.vscode
css
storybook-static
```

**.npmignore**
```
node_modules
.vscode
storybook-static
```

That way the `css` folder won't be included in commits, but it will be included when we publish to npm. 😉

**Comment by evexoio** [comment]
@trezy ok I get you now, npm goes with `.gitignore` if `.npmignore` is not found. thanks 🙌

**Pull request merged**
